dist: xenial   # required for Python >= 3.7
language: python
services: mysql
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  #TODO: add script to run test HERE
  - echo
# Push the results back to codecov
after_success:
  - python -m codecov